// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: vector_database.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DistanceMetric defines the distance metric for vector search operations
type DistanceMetric int32

const (
	DistanceMetric_EUCLIDEAN   DistanceMetric = 0 // Euclidean distance (L2 norm)
	DistanceMetric_COSINE      DistanceMetric = 1 // Cosine similarity distance
	DistanceMetric_DOT_PRODUCT DistanceMetric = 2 // Dot product distance
	DistanceMetric_MANHATTAN   DistanceMetric = 3 // Manhattan distance (L1 norm)
)

// Enum value maps for DistanceMetric.
var (
	DistanceMetric_name = map[int32]string{
		0: "EUCLIDEAN",
		1: "COSINE",
		2: "DOT_PRODUCT",
		3: "MANHATTAN",
	}
	DistanceMetric_value = map[string]int32{
		"EUCLIDEAN":   0,
		"COSINE":      1,
		"DOT_PRODUCT": 2,
		"MANHATTAN":   3,
	}
)

func (x DistanceMetric) Enum() *DistanceMetric {
	p := new(DistanceMetric)
	*p = x
	return p
}

func (x DistanceMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistanceMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_database_proto_enumTypes[0].Descriptor()
}

func (DistanceMetric) Type() protoreflect.EnumType {
	return &file_vector_database_proto_enumTypes[0]
}

func (x DistanceMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistanceMetric.Descriptor instead.
func (DistanceMetric) EnumDescriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{0}
}

// Database represents a vector database instance
type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // Unique database name
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Creation timestamp (Unix seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_vector_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Collection represents a collection of vectors within a database
type Collection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                               // Unique collection name
	DatabaseName    string                 `protobuf:"bytes,2,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`           // Parent database name
	VectorDimension int32                  `protobuf:"varint,4,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"` // Dimension of vectors in this collection
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                   // Creation timestamp (Unix seconds)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_vector_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{1}
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *Collection) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *Collection) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Point represents a single vector point in a collection
type Point struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // Unique point identifier
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Parent collection name
	DatabaseName   string                 `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`       // Parent database name
	Vector         []float32              `protobuf:"fixed32,4,rep,packed,name=vector,proto3" json:"vector,omitempty"`                              // Vector values
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // Creation timestamp (Unix seconds)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_vector_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Point) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *Point) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *Point) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Point) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// NearestPoint represents a point with its distance from a query vector
type NearestPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`         // The point data
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"` // Distance from query vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearestPoint) Reset() {
	*x = NearestPoint{}
	mi := &file_vector_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearestPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearestPoint) ProtoMessage() {}

func (x *NearestPoint) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearestPoint.ProtoReflect.Descriptor instead.
func (*NearestPoint) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{3}
}

func (x *NearestPoint) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *NearestPoint) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// ListDatabasesRequest requests a paginated list of databases
type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // Page number (0-indexed)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Number of results per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_vector_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatabasesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDatabasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListDatabasesResponse returns a paginated list of databases
type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*Database            `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"` // List of databases
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`        // Total number of databases
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_vector_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{5}
}

func (x *ListDatabasesResponse) GetDatabases() []*Database {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *ListDatabasesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetDatabaseRequest requests a specific database by name
type GetDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"` // Name of the database to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_vector_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{6}
}

func (x *GetDatabaseRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

// GetDatabaseResponse returns a specific database
type GetDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"` // The requested database
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_vector_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatabaseResponse) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

// ListCollectionsRequest requests a paginated list of collections
type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"` // Parent database name
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                                    // Page number (0-indexed)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Number of results per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_vector_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{8}
}

func (x *ListCollectionsRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *ListCollectionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListCollectionsResponse returns a paginated list of collections
type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"` // List of collections
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`            // Total number of collections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_vector_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{9}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetCollectionRequest requests a specific collection by name
type GetCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName   string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`       // Parent database name
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Name of the collection to retrieve
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_vector_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{10}
}

func (x *GetCollectionRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *GetCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

// GetCollectionResponse returns a specific collection
type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // The requested collection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_vector_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{11}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// GetPointRequest requests a specific point by ID
type GetPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName   string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`       // Parent database name
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Parent collection name
	PointId        string                 `protobuf:"bytes,3,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`                      // ID of the point to retrieve
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPointRequest) Reset() {
	*x = GetPointRequest{}
	mi := &file_vector_database_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointRequest) ProtoMessage() {}

func (x *GetPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointRequest.ProtoReflect.Descriptor instead.
func (*GetPointRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{12}
}

func (x *GetPointRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *GetPointRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetPointRequest) GetPointId() string {
	if x != nil {
		return x.PointId
	}
	return ""
}

// GetPointResponse returns a specific point
type GetPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"` // The requested point
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointResponse) Reset() {
	*x = GetPointResponse{}
	mi := &file_vector_database_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointResponse) ProtoMessage() {}

func (x *GetPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointResponse.ProtoReflect.Descriptor instead.
func (*GetPointResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{13}
}

func (x *GetPointResponse) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

// SearchNearestRequest requests nearest neighbor search
type SearchNearestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName   string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`                               // Parent database name
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`                         // Parent collection name
	QueryVector    []float32              `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`                         // Query vector for similarity search
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                                                // Maximum number of results to return
	DistanceMetric DistanceMetric         `protobuf:"varint,5,opt,name=distance_metric,json=distanceMetric,proto3,enum=pb.DistanceMetric" json:"distance_metric,omitempty"` // Distance metric to use for search
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchNearestRequest) Reset() {
	*x = SearchNearestRequest{}
	mi := &file_vector_database_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNearestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNearestRequest) ProtoMessage() {}

func (x *SearchNearestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNearestRequest.ProtoReflect.Descriptor instead.
func (*SearchNearestRequest) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{14}
}

func (x *SearchNearestRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *SearchNearestRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchNearestRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchNearestRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchNearestRequest) GetDistanceMetric() DistanceMetric {
	if x != nil {
		return x.DistanceMetric
	}
	return DistanceMetric_EUCLIDEAN
}

// SearchNearestResponse returns nearest neighbor search results
type SearchNearestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*NearestPoint        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                                             // List of nearest points with distances
	TotalMatches   int32                  `protobuf:"varint,4,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`                              // Total number of matching points
	DistanceMetric DistanceMetric         `protobuf:"varint,5,opt,name=distance_metric,json=distanceMetric,proto3,enum=pb.DistanceMetric" json:"distance_metric,omitempty"` // Distance metric used in search
	QueryVector    []float32              `protobuf:"fixed32,6,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`                         // Echo of the query vector
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchNearestResponse) Reset() {
	*x = SearchNearestResponse{}
	mi := &file_vector_database_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNearestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNearestResponse) ProtoMessage() {}

func (x *SearchNearestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_database_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNearestResponse.ProtoReflect.Descriptor instead.
func (*SearchNearestResponse) Descriptor() ([]byte, []int) {
	return file_vector_database_proto_rawDescGZIP(), []int{15}
}

func (x *SearchNearestResponse) GetResults() []*NearestPoint {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchNearestResponse) GetTotalMatches() int32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *SearchNearestResponse) GetDistanceMetric() DistanceMetric {
	if x != nil {
		return x.DistanceMetric
	}
	return DistanceMetric_EUCLIDEAN
}

func (x *SearchNearestResponse) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

var File_vector_database_proto protoreflect.FileDescriptor

const file_vector_database_proto_rawDesc = "" +
	"\n" +
	"\x15vector_database.proto\x12\x02pb\"=\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x8f\x01\n" +
	"\n" +
	"Collection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdatabase_name\x18\x02 \x01(\tR\fdatabaseName\x12)\n" +
	"\x10vector_dimension\x18\x04 \x01(\x05R\x0fvectorDimension\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x9c\x01\n" +
	"\x05Point\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\x12\x16\n" +
	"\x06vector\x18\x04 \x03(\x02R\x06vector\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"K\n" +
	"\fNearestPoint\x12\x1f\n" +
	"\x05point\x18\x01 \x01(\v2\t.pb.PointR\x05point\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"@\n" +
	"\x14ListDatabasesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Y\n" +
	"\x15ListDatabasesResponse\x12*\n" +
	"\tdatabases\x18\x01 \x03(\v2\f.pb.DatabaseR\tdatabases\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\x12GetDatabaseRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\"?\n" +
	"\x13GetDatabaseResponse\x12(\n" +
	"\bdatabase\x18\x01 \x01(\v2\f.pb.DatabaseR\bdatabase\"g\n" +
	"\x16ListCollectionsRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"a\n" +
	"\x17ListCollectionsResponse\x120\n" +
	"\vcollections\x18\x01 \x03(\v2\x0e.pb.CollectionR\vcollections\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"d\n" +
	"\x14GetCollectionRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\"G\n" +
	"\x15GetCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x0e.pb.CollectionR\n" +
	"collection\"z\n" +
	"\x0fGetPointRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x19\n" +
	"\bpoint_id\x18\x03 \x01(\tR\apointId\"3\n" +
	"\x10GetPointResponse\x12\x1f\n" +
	"\x05point\x18\x01 \x01(\v2\t.pb.PointR\x05point\"\xda\x01\n" +
	"\x14SearchNearestRequest\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12!\n" +
	"\fquery_vector\x18\x03 \x03(\x02R\vqueryVector\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12;\n" +
	"\x0fdistance_metric\x18\x05 \x01(\x0e2\x12.pb.DistanceMetricR\x0edistanceMetric\"\xc8\x01\n" +
	"\x15SearchNearestResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.pb.NearestPointR\aresults\x12#\n" +
	"\rtotal_matches\x18\x04 \x01(\x05R\ftotalMatches\x12;\n" +
	"\x0fdistance_metric\x18\x05 \x01(\x0e2\x12.pb.DistanceMetricR\x0edistanceMetric\x12!\n" +
	"\fquery_vector\x18\x06 \x03(\x02R\vqueryVector*K\n" +
	"\x0eDistanceMetric\x12\r\n" +
	"\tEUCLIDEAN\x10\x00\x12\n" +
	"\n" +
	"\x06COSINE\x10\x01\x12\x0f\n" +
	"\vDOT_PRODUCT\x10\x02\x12\r\n" +
	"\tMANHATTAN\x10\x032\x9b\x01\n" +
	"\x0fDatabaseService\x12F\n" +
	"\rListDatabases\x12\x18.pb.ListDatabasesRequest\x1a\x19.pb.ListDatabasesResponse\"\x00\x12@\n" +
	"\vGetDatabase\x12\x16.pb.GetDatabaseRequest\x1a\x17.pb.GetDatabaseResponse\"\x002\xa9\x01\n" +
	"\x11CollectionService\x12L\n" +
	"\x0fListCollections\x12\x1a.pb.ListCollectionsRequest\x1a\x1b.pb.ListCollectionsResponse\"\x00\x12F\n" +
	"\rGetCollection\x12\x18.pb.GetCollectionRequest\x1a\x19.pb.GetCollectionResponse\"\x002\x8f\x01\n" +
	"\fPointService\x127\n" +
	"\bGetPoint\x12\x13.pb.GetPointRequest\x1a\x14.pb.GetPointResponse\"\x00\x12F\n" +
	"\rSearchNearest\x12\x18.pb.SearchNearestRequest\x1a\x19.pb.SearchNearestResponse\"\x00B]\n" +
	"\x17com.vishgupt.rainier.pbB\x13VectorDatabaseProtoP\x01Z+github.com/vishgupt/rainier/src/internal/pbb\x06proto3"

var (
	file_vector_database_proto_rawDescOnce sync.Once
	file_vector_database_proto_rawDescData []byte
)

func file_vector_database_proto_rawDescGZIP() []byte {
	file_vector_database_proto_rawDescOnce.Do(func() {
		file_vector_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_database_proto_rawDesc), len(file_vector_database_proto_rawDesc)))
	})
	return file_vector_database_proto_rawDescData
}

var file_vector_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vector_database_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_vector_database_proto_goTypes = []any{
	(DistanceMetric)(0),             // 0: pb.DistanceMetric
	(*Database)(nil),                // 1: pb.Database
	(*Collection)(nil),              // 2: pb.Collection
	(*Point)(nil),                   // 3: pb.Point
	(*NearestPoint)(nil),            // 4: pb.NearestPoint
	(*ListDatabasesRequest)(nil),    // 5: pb.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),   // 6: pb.ListDatabasesResponse
	(*GetDatabaseRequest)(nil),      // 7: pb.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),     // 8: pb.GetDatabaseResponse
	(*ListCollectionsRequest)(nil),  // 9: pb.ListCollectionsRequest
	(*ListCollectionsResponse)(nil), // 10: pb.ListCollectionsResponse
	(*GetCollectionRequest)(nil),    // 11: pb.GetCollectionRequest
	(*GetCollectionResponse)(nil),   // 12: pb.GetCollectionResponse
	(*GetPointRequest)(nil),         // 13: pb.GetPointRequest
	(*GetPointResponse)(nil),        // 14: pb.GetPointResponse
	(*SearchNearestRequest)(nil),    // 15: pb.SearchNearestRequest
	(*SearchNearestResponse)(nil),   // 16: pb.SearchNearestResponse
}
var file_vector_database_proto_depIdxs = []int32{
	3,  // 0: pb.NearestPoint.point:type_name -> pb.Point
	1,  // 1: pb.ListDatabasesResponse.databases:type_name -> pb.Database
	1,  // 2: pb.GetDatabaseResponse.database:type_name -> pb.Database
	2,  // 3: pb.ListCollectionsResponse.collections:type_name -> pb.Collection
	2,  // 4: pb.GetCollectionResponse.collection:type_name -> pb.Collection
	3,  // 5: pb.GetPointResponse.point:type_name -> pb.Point
	0,  // 6: pb.SearchNearestRequest.distance_metric:type_name -> pb.DistanceMetric
	4,  // 7: pb.SearchNearestResponse.results:type_name -> pb.NearestPoint
	0,  // 8: pb.SearchNearestResponse.distance_metric:type_name -> pb.DistanceMetric
	5,  // 9: pb.DatabaseService.ListDatabases:input_type -> pb.ListDatabasesRequest
	7,  // 10: pb.DatabaseService.GetDatabase:input_type -> pb.GetDatabaseRequest
	9,  // 11: pb.CollectionService.ListCollections:input_type -> pb.ListCollectionsRequest
	11, // 12: pb.CollectionService.GetCollection:input_type -> pb.GetCollectionRequest
	13, // 13: pb.PointService.GetPoint:input_type -> pb.GetPointRequest
	15, // 14: pb.PointService.SearchNearest:input_type -> pb.SearchNearestRequest
	6,  // 15: pb.DatabaseService.ListDatabases:output_type -> pb.ListDatabasesResponse
	8,  // 16: pb.DatabaseService.GetDatabase:output_type -> pb.GetDatabaseResponse
	10, // 17: pb.CollectionService.ListCollections:output_type -> pb.ListCollectionsResponse
	12, // 18: pb.CollectionService.GetCollection:output_type -> pb.GetCollectionResponse
	14, // 19: pb.PointService.GetPoint:output_type -> pb.GetPointResponse
	16, // 20: pb.PointService.SearchNearest:output_type -> pb.SearchNearestResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vector_database_proto_init() }
func file_vector_database_proto_init() {
	if File_vector_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_database_proto_rawDesc), len(file_vector_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_vector_database_proto_goTypes,
		DependencyIndexes: file_vector_database_proto_depIdxs,
		EnumInfos:         file_vector_database_proto_enumTypes,
		MessageInfos:      file_vector_database_proto_msgTypes,
	}.Build()
	File_vector_database_proto = out.File
	file_vector_database_proto_goTypes = nil
	file_vector_database_proto_depIdxs = nil
}
